export const favoritesTypes = {
  FETCH_FAVORITES_REQUEST: "FETCH_FAVORITES_REQUEST",
  FETCH_FAVORITES_SUCCESS: "FETCH_FAVORITES_SUCCESS",
  FETCH_FAVORITES_FAILURE: "FETCH_FAVORITES_FAILURE",

  ADD_TO_FAVORITES_REQUEST: "ADD_TO_FAVORITES_REQUEST",
  ADD_TO_FAVORITES_SUCCESS: "ADD_TO_FAVORITES_SUCCESS",
  ADD_TO_FAVORITES_FAILURE: "ADD_TO_FAVORITES_FAILURE",

  REMOVE_FROM_FAVORITES_REQUEST: "REMOVE_FROM_FAVORITES_REQUEST",
  REMOVE_FROM_FAVORITES_SUCCESS: "REMOVE_FROM_FAVORITES_SUCCESS",
  REMOVE_FROM_FAVORITES_FAILURE: "REMOVE_FROM_FAVORITES_FAILURE",
}