export const userTypes = {
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",
  FETCH_CART_REQUEST: "FETCH_CART_REQUEST",
  FETCH_CART_FAILURE: "FETCH_CART_FAILURE",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  USER_REMOVE_FROM_CART: "USER_REMOVE_FROM_CART"

}